services:
  server:
    restart: always
    image: ghcr.io/stellarcyber-cse/coverage-analyzer-ng-server:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    stdin_open: true
    tty: true
    env_file:
      - path: ../environment/env.server
        required: true
      - path: ../environment/env.server.override
        required: false
